services:
  app:
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    command: php-fpm
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_DATABASE: service_dept_app
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: laravel-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.4
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: service_dept_app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
